"""initial schema —— 全部 19 张业务表的结构

Revision ID: 0001
Revises:
Create Date: 2026-09-25 04:38:06.365341+00:00

本迁移一次性建全 docs/02 §3 的全部表结构（M1 虽然只用其中几张，
但一次建全可以避免后面反复改迁移）。

结构要点：
  - 循环外键 `tools.current_version_id` / `pending_version_id` /
    `cover_image_id` 用 `use_alter=True`，建表后单独 ADD CONSTRAINT
  - `tool_versions` 上的「每个 tool 至多一个 is_current」部分唯一索引
    用 `op.execute()` 手写 DDL（见 upgrade() 末尾）
  - 枚举一律用 `String(n)` + `CHECK` 约束，不用数据库原生 ENUM
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('ix_categories_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_categories_sort_order', ['sort_order'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('auth_source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active','disabled')", name=op.f('ck_users_status')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_users_created_by_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('external_id', name=op.f('uq_users_external_id')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_status', ['status'], unique=False)

    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_api_tokens_created_by_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], name=op.f('fk_api_tokens_revoked_by_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_api_tokens_created_by', ['created_by_id'], unique=False)

    op.create_table('approval_whitelist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_approval_whitelist_added_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_approval_whitelist_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_approval_whitelist'))
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_auth_sessions_refresh_token_hash'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_auth_sessions_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_auth_sessions_user', ['user_id'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_groups_created_by_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_groups_name'))
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_system_settings_updated_by_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tags_created_by_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('tool_type', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('pending_version_id', sa.Integer(), nullable=True),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.Column('webapp_url', sa.String(length=1024), nullable=True),
    sa.Column('webapp_health_url', sa.String(length=1024), nullable=True),
    sa.Column('webapp_health_status', sa.String(length=16), nullable=True),
    sa.Column('webapp_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_count', sa.BigInteger(), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_version_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('offline_reason', sa.Text(), nullable=True),
    sa.Column('version_seq', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','pending','approved','rejected','pending_update','offline')", name=op.f('ck_tools_status')),
    sa.CheckConstraint("tool_type <> 'webapp' OR webapp_url IS NOT NULL", name=op.f('ck_tools_webapp_url')),
    sa.CheckConstraint("tool_type IN ('file','webapp','skill','prompt')", name=op.f('ck_tools_type')),
    sa.CheckConstraint("visibility IN ('public','restricted','private')", name=op.f('ck_tools_visibility')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_tools_category_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cover_image_id'], ['tool_images.id'], name='fk_tools_cover_image_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['current_version_id'], ['tool_versions.id'], name='fk_tools_current_version_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_tools_deleted_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tools_owner_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pending_version_id'], ['tool_versions.id'], name='fk_tools_pending_version_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tools')),
    sa.UniqueConstraint('slug', name=op.f('uq_tools_slug'))
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index('ix_tools_category_status', ['category_id', 'status'], unique=False)
        batch_op.create_index('ix_tools_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_tools_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index('ix_tools_status_visibility', ['status', 'visibility'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_user_roles_granted_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_group_members_added_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_members_group_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_members_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_group_members'))
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index('ix_group_members_user_id', ['user_id'], unique=False)

    op.create_table('tool_acl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tool_acl_created_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_acl_tool_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_acl'))
    )
    with op.batch_alter_table('tool_acl', schema=None) as batch_op:
        batch_op.create_index('ix_tool_acl_subject', ['subject_type', 'subject_id'], unique=False)
        batch_op.create_index('uq_tool_acl_subject', ['tool_id', 'subject_type', 'subject_id'], unique=True)

    op.create_table('tool_stats_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_stats_daily_tool_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_stats_daily'))
    )
    with op.batch_alter_table('tool_stats_daily', schema=None) as batch_op:
        batch_op.create_index('ix_tool_stats_daily_date', ['stat_date'], unique=False)
        batch_op.create_index('uq_tool_stats_daily', ['tool_id', 'stat_date'], unique=True)

    op.create_table('tool_tags',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tool_tags_tag_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_tags_tool_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'tag_id', name=op.f('pk_tool_tags'))
    )
    with op.batch_alter_table('tool_tags', schema=None) as batch_op:
        batch_op.create_index('ix_tool_tags_tag_id', ['tag_id'], unique=False)

    op.create_table('tool_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('changelog_md', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('file_ext', sa.String(length=16), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('prompt_content', sa.Text(), nullable=True),
    sa.Column('skill_readme_md', sa.Text(), nullable=True),
    sa.Column('skill_manifest', sa.JSON(), nullable=True),
    sa.Column('skill_file_tree', sa.JSON(), nullable=True),
    sa.Column('skill_parse_error', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('auto_approved_rule', sa.String(length=32), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected','superseded','purged')", name=op.f('ck_tool_versions_status')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_tool_versions_approved_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_versions_tool_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_tool_versions_uploaded_by_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_versions'))
    )
    with op.batch_alter_table('tool_versions', schema=None) as batch_op:
        batch_op.create_index('ix_tool_versions_sha256', ['file_sha256'], unique=False)
        batch_op.create_index('ix_tool_versions_status', ['status'], unique=False)
        batch_op.create_index('ix_tool_versions_tool_created', ['tool_id', 'created_at'], unique=False)
        batch_op.create_index('uq_tool_versions_tool_version', ['tool_id', 'version'], unique=True)

    op.create_table('approval_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('version_from_status', sa.String(length=16), nullable=True),
    sa.Column('version_to_status', sa.String(length=16), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=128), nullable=False),
    sa.Column('is_automatic', sa.Boolean(), nullable=False),
    sa.Column('auto_rule', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_approval_records_actor_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_approval_records_tool_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['tool_versions.id'], name=op.f('fk_approval_records_version_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_records'))
    )
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.create_index('ix_approval_records_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index('ix_approval_records_actor', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_approval_records_tool_created', ['tool_id', 'created_at'], unique=False)

    op.create_table('download_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('via_api_token_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_download_logs_tool_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_download_logs_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['tool_versions.id'], name=op.f('fk_download_logs_version_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['via_api_token_id'], ['api_tokens.id'], name=op.f('fk_download_logs_via_api_token_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_logs'))
    )
    with op.batch_alter_table('download_logs', schema=None) as batch_op:
        batch_op.create_index('ix_download_logs_created', ['created_at'], unique=False)
        batch_op.create_index('ix_download_logs_tool_created', ['tool_id', 'created_at'], unique=False)
        batch_op.create_index('ix_download_logs_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('tool_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('thumb_path', sa.String(length=512), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('cover','screenshot','inline')", name=op.f('ck_tool_images_kind')),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_images_tool_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_tool_images_uploaded_by_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['tool_versions.id'], name=op.f('fk_tool_images_version_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_images'))
    )
    with op.batch_alter_table('tool_images', schema=None) as batch_op:
        batch_op.create_index('ix_tool_images_tool_kind', ['tool_id', 'kind', 'sort_order'], unique=False)

    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # 「每个 tool 至多一个 is_current = true」的**部分唯一索引**
    # ------------------------------------------------------------------
    # docs/02 §3.11 要求这条硬保证。SQLite 从 3.8.0 起支持部分索引，
    # PostgreSQL 语法完全相同，因此两边都能建。
    #
    # 之所以手写 DDL 而不用 op.create_index：Alembic 的 create_index
    # 不支持 `postgresql_where` / `sqlite_where` 之外的部分索引谓词写法，
    # 而这里要的是跨库一致的原生语法。这也是 docs/02 §3.11 的明确要求：
    # 「Alembic 里用 op.execute() 手写这段 DDL」。
    # 谓词必须写 `IS TRUE` 而不是 `= 1`：
    # PostgreSQL 的 boolean 与 integer 之间**没有**隐式比较运算符，
    # `WHERE is_current = 1` 会直接报 UndefinedFunction（M4 的 PG 演练实测）。
    # `IS TRUE` 在 SQLite 上也成立（SQLite 里 true 就是 1），跨库一致。
    op.execute(
        "CREATE UNIQUE INDEX uq_tool_versions_current "
        "ON tool_versions(tool_id) WHERE is_current IS TRUE"
    )

    # ------------------------------------------------------------------
    # 循环外键说明
    # ------------------------------------------------------------------
    # tools.current_version_id / pending_version_id / cover_image_id 与
    # tool_versions / tool_images 互为引用（docs/02 §2）。这三个约束在模型里
    # 标了 use_alter=True，由 Alembic 在建表后用 ALTER TABLE 添加
    # （见上面的 create_table 调用，约束名分别是 fk_tools_current_version_id /
    # fk_tools_pending_version_id / fk_tools_cover_image_id）。


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS uq_tool_versions_current")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_images', schema=None) as batch_op:
        batch_op.drop_index('ix_tool_images_tool_kind')

    op.drop_table('tool_images')
    with op.batch_alter_table('download_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_download_logs_user_created')
        batch_op.drop_index('ix_download_logs_tool_created')
        batch_op.drop_index('ix_download_logs_created')

    op.drop_table('download_logs')
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.drop_index('ix_approval_records_tool_created')
        batch_op.drop_index('ix_approval_records_actor')
        batch_op.drop_index('ix_approval_records_action_created')

    op.drop_table('approval_records')
    with op.batch_alter_table('tool_versions', schema=None) as batch_op:
        batch_op.drop_index('uq_tool_versions_tool_version')
        batch_op.drop_index('ix_tool_versions_tool_created')
        batch_op.drop_index('ix_tool_versions_status')
        batch_op.drop_index('ix_tool_versions_sha256')

    op.drop_table('tool_versions')
    with op.batch_alter_table('tool_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tool_tags_tag_id')

    op.drop_table('tool_tags')
    with op.batch_alter_table('tool_stats_daily', schema=None) as batch_op:
        batch_op.drop_index('uq_tool_stats_daily')
        batch_op.drop_index('ix_tool_stats_daily_date')

    op.drop_table('tool_stats_daily')
    with op.batch_alter_table('tool_acl', schema=None) as batch_op:
        batch_op.drop_index('uq_tool_acl_subject')
        batch_op.drop_index('ix_tool_acl_subject')

    op.drop_table('tool_acl')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index('ix_group_members_user_id')

    op.drop_table('group_members')
    op.drop_table('user_roles')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index('ix_tools_status_visibility')
        batch_op.drop_index('ix_tools_owner_status')
        batch_op.drop_index('ix_tools_deleted_at')
        batch_op.drop_index('ix_tools_category_status')

    op.drop_table('tools')
    op.drop_table('tags')
    op.drop_table('system_settings')
    op.drop_table('groups')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_sessions_user')
        batch_op.drop_index('ix_auth_sessions_expires')

    op.drop_table('auth_sessions')
    op.drop_table('approval_whitelist')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_api_tokens_created_by')

    op.drop_table('api_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_status')

    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_sort_order')
        batch_op.drop_index('ix_categories_is_active')

    op.drop_table('categories')
    # ### end Alembic commands ###
